n = 8;
disp(n);
H = hilb(n);
x = ones(n, 1);
b = H * x;
L = cholesky(H, n);
root = L' \ (L \ b);
r = b - H * root;
delta = root - x;
disp(norm(r, inf));
disp(norm(delta, inf));
b = b + ones(n, 1) * 1e-7;
root = L' \ (L \ b);
r = b - H * root;
delta = root - x;
disp(norm(r, inf));
disp(norm(delta, inf));

n = 10;
disp(n);
H = hilb(n);
x = ones(n, 1);
b = H * x;
L = cholesky(H, n);
root = L' \ (L \ b);
r = b - H * root;
delta = root - x;
disp(norm(r, inf));
disp(norm(delta, inf));
b = b + ones(n, 1) * 1e-7;
root = L' \ (L \ b);
r = b - H * root;
delta = root - x;
disp(norm(r, inf));
disp(norm(delta, inf));

n = 12;
disp(n);
H = hilb(n);
x = ones(n, 1);
b = H * x;
L = cholesky(H, n);
root = L' \ (L \ b);
r = b - H * root;
delta = root - x;
disp(norm(r, inf));
disp(norm(delta, inf));
b = b + ones(n, 1) * 1e-7;
root = L' \ (L \ b);
r = b - H * root;
delta = root - x;
disp(norm(r, inf));
disp(norm(delta, inf));
