# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inverted',
            fields=[
                ('word', models.TextField(primary_key=True, serialize=False)),
                ('in_title', models.TextField()),
                ('in_content', models.TextField()),
            ],
            options={
                'db_table': 'inverted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thuspideritem',
            fields=[
                ('content', models.TextField()),
                ('date', models.TextField()),
                ('news_id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'ThuSpiderItem',
                'managed': False,
            },
        ),
    ]
