/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *pushButton_1;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QPushButton *pushButton_37;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QPushButton *pushButton_45;
    QPushButton *pushButton_46;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QPushButton *pushButton_49;
    QPushButton *pushButton_50;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;
    QPushButton *pushButton_53;
    QPushButton *pushButton_54;
    QPushButton *pushButton_55;
    QPushButton *pushButton_56;
    QPushButton *pushButton_57;
    QPushButton *pushButton_58;
    QPushButton *pushButton_59;
    QPushButton *pushButton_60;
    QPushButton *pushButton_61;
    QPushButton *pushButton_62;
    QPushButton *pushButton_63;
    QPushButton *pushButton_64;
    QPushButton *pushButton_65;
    QPushButton *pushButton_66;
    QPushButton *pushButton_67;
    QPushButton *pushButton_68;
    QPushButton *pushButton_69;
    QPushButton *pushButton_70;
    QPushButton *pushButton_71;
    QPushButton *pushButton_72;
    QPushButton *pushButton_73;
    QPushButton *pushButton_74;
    QPushButton *pushButton_75;
    QPushButton *pushButton_76;
    QPushButton *pushButton_77;
    QPushButton *pushButton_78;
    QPushButton *pushButton_79;
    QPushButton *pushButton_80;
    QPushButton *pushButton_81;
    QPushButton *pushButton_82;
    QPushButton *pushButton_83;
    QPushButton *pushButton_84;
    QPushButton *pushButton_85;
    QPushButton *pushButton_86;
    QPushButton *pushButton_87;
    QPushButton *pushButton_88;
    QPushButton *pushButton_89;
    QPushButton *pushButton_90;
    QPushButton *pushButton_91;
    QPushButton *pushButton_92;
    QPushButton *pushButton_93;
    QPushButton *pushButton_94;
    QPushButton *pushButton_95;
    QPushButton *pushButton_96;
    QPushButton *pushButton_97;
    QPushButton *pushButton_98;
    QPushButton *pushButton_99;
    QPushButton *pushButton_100;
    QLabel *label1;
    QPushButton *quitButton;
    QLabel *label_2;
    QPushButton *equa;
    QPushButton *escape;
    QPushButton *link;
    QPushButton *sebut;
    QPushButton *bgmbut;
    QLineEdit *echess;
    QLineEdit *ochess;
    QPushButton *testdel;
    QPushButton *testmov;
    QPushButton *severon;
    QPushButton *changeGod;
    QPushButton *testend;
    QPushButton *teststart;
    QLabel *link1;
    QLabel *quitButton1;
    QLabel *equa1;
    QLabel *escape1;
    QLabel *who;
    QLabel *walk;
    QLabel *chesso;
    QLabel *chesse;
    QLabel *se;
    QLabel *bgm;
    QLabel *sever;
    QLabel *qh1;
    QLabel *qh2;
    QLabel *se_2;
    QLabel *bgm_2;
    QLabel *sever_2;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1000, 600);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        pushButton_1 = new QPushButton(centralWidget);
        pushButton_1->setObjectName(QStringLiteral("pushButton_1"));
        pushButton_1->setGeometry(QRect(320, 150, 40, 40));
        pushButton_1->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(360, 150, 40, 40));
        pushButton_2->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(400, 150, 40, 40));
        pushButton_3->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(440, 150, 40, 40));
        pushButton_4->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_5 = new QPushButton(centralWidget);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(480, 150, 40, 40));
        pushButton_5->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_6 = new QPushButton(centralWidget);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(520, 150, 40, 40));
        pushButton_6->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_7 = new QPushButton(centralWidget);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(560, 150, 40, 40));
        pushButton_7->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_8 = new QPushButton(centralWidget);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(600, 150, 40, 40));
        pushButton_8->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_9 = new QPushButton(centralWidget);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(640, 150, 40, 40));
        pushButton_9->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_10 = new QPushButton(centralWidget);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(680, 150, 40, 40));
        pushButton_10->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_11 = new QPushButton(centralWidget);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(320, 190, 40, 40));
        pushButton_11->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_12 = new QPushButton(centralWidget);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(360, 190, 40, 40));
        pushButton_12->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_13 = new QPushButton(centralWidget);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(400, 190, 40, 40));
        pushButton_13->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_14 = new QPushButton(centralWidget);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(440, 190, 40, 40));
        pushButton_14->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_15 = new QPushButton(centralWidget);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(480, 190, 40, 40));
        pushButton_15->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_16 = new QPushButton(centralWidget);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(520, 190, 40, 40));
        pushButton_16->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_17 = new QPushButton(centralWidget);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(560, 190, 40, 40));
        pushButton_17->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_18 = new QPushButton(centralWidget);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(600, 190, 40, 40));
        pushButton_18->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_19 = new QPushButton(centralWidget);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(640, 190, 40, 40));
        pushButton_19->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_20 = new QPushButton(centralWidget);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(680, 190, 40, 40));
        pushButton_20->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_21 = new QPushButton(centralWidget);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(320, 230, 40, 40));
        pushButton_21->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_22 = new QPushButton(centralWidget);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(360, 230, 40, 40));
        pushButton_22->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_23 = new QPushButton(centralWidget);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(400, 230, 40, 40));
        pushButton_23->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_24 = new QPushButton(centralWidget);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(440, 230, 40, 40));
        pushButton_24->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_25 = new QPushButton(centralWidget);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(480, 230, 40, 40));
        pushButton_25->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_26 = new QPushButton(centralWidget);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(520, 230, 40, 40));
        pushButton_26->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_27 = new QPushButton(centralWidget);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(560, 230, 40, 40));
        pushButton_27->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_28 = new QPushButton(centralWidget);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(600, 230, 40, 40));
        pushButton_28->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_29 = new QPushButton(centralWidget);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(640, 230, 40, 40));
        pushButton_29->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_30 = new QPushButton(centralWidget);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(680, 230, 40, 40));
        pushButton_30->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_31 = new QPushButton(centralWidget);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(320, 270, 40, 40));
        pushButton_31->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_32 = new QPushButton(centralWidget);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(360, 270, 40, 40));
        pushButton_32->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_33 = new QPushButton(centralWidget);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(400, 270, 40, 40));
        pushButton_33->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_34 = new QPushButton(centralWidget);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(440, 270, 40, 40));
        pushButton_34->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_35 = new QPushButton(centralWidget);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(480, 270, 40, 40));
        pushButton_35->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_36 = new QPushButton(centralWidget);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(520, 270, 40, 40));
        pushButton_36->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_37 = new QPushButton(centralWidget);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(560, 270, 40, 40));
        pushButton_37->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_38 = new QPushButton(centralWidget);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(600, 270, 40, 40));
        pushButton_38->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_39 = new QPushButton(centralWidget);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(640, 270, 40, 40));
        pushButton_39->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_40 = new QPushButton(centralWidget);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(680, 270, 40, 40));
        pushButton_40->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_41 = new QPushButton(centralWidget);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(320, 310, 40, 40));
        pushButton_41->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_42 = new QPushButton(centralWidget);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(360, 310, 40, 40));
        pushButton_42->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_43 = new QPushButton(centralWidget);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(400, 310, 40, 40));
        pushButton_43->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_44 = new QPushButton(centralWidget);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(440, 310, 40, 40));
        pushButton_44->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_45 = new QPushButton(centralWidget);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(480, 310, 40, 40));
        pushButton_45->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_46 = new QPushButton(centralWidget);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(520, 310, 40, 40));
        pushButton_46->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_47 = new QPushButton(centralWidget);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(560, 310, 40, 40));
        pushButton_47->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_48 = new QPushButton(centralWidget);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(600, 310, 40, 40));
        pushButton_48->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_49 = new QPushButton(centralWidget);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(640, 310, 40, 40));
        pushButton_49->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_50 = new QPushButton(centralWidget);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(680, 310, 40, 40));
        pushButton_50->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_51 = new QPushButton(centralWidget);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(320, 350, 40, 40));
        pushButton_51->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_52 = new QPushButton(centralWidget);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(360, 350, 40, 40));
        pushButton_52->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_53 = new QPushButton(centralWidget);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(400, 350, 40, 40));
        pushButton_53->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_54 = new QPushButton(centralWidget);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(440, 350, 40, 40));
        pushButton_54->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_55 = new QPushButton(centralWidget);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(480, 350, 40, 40));
        pushButton_55->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_56 = new QPushButton(centralWidget);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(520, 350, 40, 40));
        pushButton_56->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_57 = new QPushButton(centralWidget);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(560, 350, 40, 40));
        pushButton_57->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_58 = new QPushButton(centralWidget);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(600, 350, 40, 40));
        pushButton_58->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_59 = new QPushButton(centralWidget);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(640, 350, 40, 40));
        pushButton_59->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_60 = new QPushButton(centralWidget);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(680, 350, 40, 40));
        pushButton_60->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_61 = new QPushButton(centralWidget);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(320, 390, 40, 40));
        pushButton_61->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_62 = new QPushButton(centralWidget);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(360, 390, 40, 40));
        pushButton_62->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_63 = new QPushButton(centralWidget);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(400, 390, 40, 40));
        pushButton_63->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_64 = new QPushButton(centralWidget);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(440, 390, 40, 40));
        pushButton_64->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_65 = new QPushButton(centralWidget);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(480, 390, 40, 40));
        pushButton_65->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_66 = new QPushButton(centralWidget);
        pushButton_66->setObjectName(QStringLiteral("pushButton_66"));
        pushButton_66->setGeometry(QRect(520, 390, 40, 40));
        pushButton_66->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_67 = new QPushButton(centralWidget);
        pushButton_67->setObjectName(QStringLiteral("pushButton_67"));
        pushButton_67->setGeometry(QRect(560, 390, 40, 40));
        pushButton_67->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_68 = new QPushButton(centralWidget);
        pushButton_68->setObjectName(QStringLiteral("pushButton_68"));
        pushButton_68->setGeometry(QRect(600, 390, 40, 40));
        pushButton_68->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_69 = new QPushButton(centralWidget);
        pushButton_69->setObjectName(QStringLiteral("pushButton_69"));
        pushButton_69->setGeometry(QRect(640, 390, 40, 40));
        pushButton_69->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_70 = new QPushButton(centralWidget);
        pushButton_70->setObjectName(QStringLiteral("pushButton_70"));
        pushButton_70->setGeometry(QRect(680, 390, 40, 40));
        pushButton_70->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_71 = new QPushButton(centralWidget);
        pushButton_71->setObjectName(QStringLiteral("pushButton_71"));
        pushButton_71->setGeometry(QRect(320, 430, 40, 40));
        pushButton_71->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_72 = new QPushButton(centralWidget);
        pushButton_72->setObjectName(QStringLiteral("pushButton_72"));
        pushButton_72->setGeometry(QRect(360, 430, 40, 40));
        pushButton_72->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_73 = new QPushButton(centralWidget);
        pushButton_73->setObjectName(QStringLiteral("pushButton_73"));
        pushButton_73->setGeometry(QRect(400, 430, 40, 40));
        pushButton_73->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_74 = new QPushButton(centralWidget);
        pushButton_74->setObjectName(QStringLiteral("pushButton_74"));
        pushButton_74->setGeometry(QRect(440, 430, 40, 40));
        pushButton_74->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_75 = new QPushButton(centralWidget);
        pushButton_75->setObjectName(QStringLiteral("pushButton_75"));
        pushButton_75->setGeometry(QRect(480, 430, 40, 40));
        pushButton_75->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_76 = new QPushButton(centralWidget);
        pushButton_76->setObjectName(QStringLiteral("pushButton_76"));
        pushButton_76->setGeometry(QRect(520, 430, 40, 40));
        pushButton_76->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_77 = new QPushButton(centralWidget);
        pushButton_77->setObjectName(QStringLiteral("pushButton_77"));
        pushButton_77->setGeometry(QRect(560, 430, 40, 40));
        pushButton_77->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_78 = new QPushButton(centralWidget);
        pushButton_78->setObjectName(QStringLiteral("pushButton_78"));
        pushButton_78->setGeometry(QRect(600, 430, 40, 40));
        pushButton_78->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_79 = new QPushButton(centralWidget);
        pushButton_79->setObjectName(QStringLiteral("pushButton_79"));
        pushButton_79->setGeometry(QRect(640, 430, 40, 40));
        pushButton_79->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_80 = new QPushButton(centralWidget);
        pushButton_80->setObjectName(QStringLiteral("pushButton_80"));
        pushButton_80->setGeometry(QRect(680, 430, 40, 40));
        pushButton_80->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_81 = new QPushButton(centralWidget);
        pushButton_81->setObjectName(QStringLiteral("pushButton_81"));
        pushButton_81->setGeometry(QRect(320, 470, 40, 40));
        pushButton_81->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_82 = new QPushButton(centralWidget);
        pushButton_82->setObjectName(QStringLiteral("pushButton_82"));
        pushButton_82->setGeometry(QRect(360, 470, 40, 40));
        pushButton_82->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_83 = new QPushButton(centralWidget);
        pushButton_83->setObjectName(QStringLiteral("pushButton_83"));
        pushButton_83->setGeometry(QRect(400, 470, 40, 40));
        pushButton_83->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_84 = new QPushButton(centralWidget);
        pushButton_84->setObjectName(QStringLiteral("pushButton_84"));
        pushButton_84->setGeometry(QRect(440, 470, 40, 40));
        pushButton_84->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_85 = new QPushButton(centralWidget);
        pushButton_85->setObjectName(QStringLiteral("pushButton_85"));
        pushButton_85->setGeometry(QRect(480, 470, 40, 40));
        pushButton_85->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_86 = new QPushButton(centralWidget);
        pushButton_86->setObjectName(QStringLiteral("pushButton_86"));
        pushButton_86->setGeometry(QRect(520, 470, 40, 40));
        pushButton_86->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_87 = new QPushButton(centralWidget);
        pushButton_87->setObjectName(QStringLiteral("pushButton_87"));
        pushButton_87->setGeometry(QRect(560, 470, 40, 40));
        pushButton_87->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_88 = new QPushButton(centralWidget);
        pushButton_88->setObjectName(QStringLiteral("pushButton_88"));
        pushButton_88->setGeometry(QRect(600, 470, 40, 40));
        pushButton_88->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_89 = new QPushButton(centralWidget);
        pushButton_89->setObjectName(QStringLiteral("pushButton_89"));
        pushButton_89->setGeometry(QRect(640, 470, 40, 40));
        pushButton_89->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_90 = new QPushButton(centralWidget);
        pushButton_90->setObjectName(QStringLiteral("pushButton_90"));
        pushButton_90->setGeometry(QRect(680, 470, 40, 40));
        pushButton_90->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_91 = new QPushButton(centralWidget);
        pushButton_91->setObjectName(QStringLiteral("pushButton_91"));
        pushButton_91->setGeometry(QRect(320, 510, 40, 40));
        pushButton_91->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_92 = new QPushButton(centralWidget);
        pushButton_92->setObjectName(QStringLiteral("pushButton_92"));
        pushButton_92->setGeometry(QRect(360, 510, 40, 40));
        pushButton_92->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_93 = new QPushButton(centralWidget);
        pushButton_93->setObjectName(QStringLiteral("pushButton_93"));
        pushButton_93->setGeometry(QRect(400, 510, 40, 40));
        pushButton_93->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_94 = new QPushButton(centralWidget);
        pushButton_94->setObjectName(QStringLiteral("pushButton_94"));
        pushButton_94->setGeometry(QRect(440, 510, 40, 40));
        pushButton_94->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_95 = new QPushButton(centralWidget);
        pushButton_95->setObjectName(QStringLiteral("pushButton_95"));
        pushButton_95->setGeometry(QRect(480, 510, 40, 40));
        pushButton_95->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_96 = new QPushButton(centralWidget);
        pushButton_96->setObjectName(QStringLiteral("pushButton_96"));
        pushButton_96->setGeometry(QRect(520, 510, 40, 40));
        pushButton_96->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_97 = new QPushButton(centralWidget);
        pushButton_97->setObjectName(QStringLiteral("pushButton_97"));
        pushButton_97->setGeometry(QRect(560, 510, 40, 40));
        pushButton_97->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_98 = new QPushButton(centralWidget);
        pushButton_98->setObjectName(QStringLiteral("pushButton_98"));
        pushButton_98->setGeometry(QRect(600, 510, 40, 40));
        pushButton_98->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_99 = new QPushButton(centralWidget);
        pushButton_99->setObjectName(QStringLiteral("pushButton_99"));
        pushButton_99->setGeometry(QRect(640, 510, 40, 40));
        pushButton_99->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_100 = new QPushButton(centralWidget);
        pushButton_100->setObjectName(QStringLiteral("pushButton_100"));
        pushButton_100->setGeometry(QRect(680, 510, 40, 40));
        pushButton_100->setCursor(QCursor(Qt::PointingHandCursor));
        label1 = new QLabel(centralWidget);
        label1->setObjectName(QStringLiteral("label1"));
        label1->setGeometry(QRect(0, 0, 1000, 600));
        quitButton = new QPushButton(centralWidget);
        quitButton->setObjectName(QStringLiteral("quitButton"));
        quitButton->setGeometry(QRect(870, 350, 80, 80));
        quitButton->setCursor(QCursor(Qt::PointingHandCursor));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(0, 0, 156, 152));
        equa = new QPushButton(centralWidget);
        equa->setObjectName(QStringLiteral("equa"));
        equa->setGeometry(QRect(760, 470, 80, 80));
        equa->setCursor(QCursor(Qt::PointingHandCursor));
        escape = new QPushButton(centralWidget);
        escape->setObjectName(QStringLiteral("escape"));
        escape->setGeometry(QRect(870, 470, 80, 80));
        escape->setCursor(QCursor(Qt::PointingHandCursor));
        link = new QPushButton(centralWidget);
        link->setObjectName(QStringLiteral("link"));
        link->setGeometry(QRect(760, 350, 80, 80));
        link->setCursor(QCursor(Qt::PointingHandCursor));
        sebut = new QPushButton(centralWidget);
        sebut->setObjectName(QStringLiteral("sebut"));
        sebut->setGeometry(QRect(760, 160, 80, 20));
        sebut->setCursor(QCursor(Qt::PointingHandCursor));
        bgmbut = new QPushButton(centralWidget);
        bgmbut->setObjectName(QStringLiteral("bgmbut"));
        bgmbut->setGeometry(QRect(760, 200, 80, 20));
        bgmbut->setCursor(QCursor(Qt::PointingHandCursor));
        echess = new QLineEdit(centralWidget);
        echess->setObjectName(QStringLiteral("echess"));
        echess->setGeometry(QRect(160, 150, 120, 40));
        QFont font;
        font.setFamily(QStringLiteral("Adobe Caslon Pro"));
        font.setPointSize(20);
        font.setBold(true);
        font.setWeight(75);
        echess->setFont(font);
        echess->setCursor(QCursor(Qt::ArrowCursor));
        ochess = new QLineEdit(centralWidget);
        ochess->setObjectName(QStringLiteral("ochess"));
        ochess->setGeometry(QRect(160, 510, 120, 40));
        ochess->setFont(font);
        ochess->setCursor(QCursor(Qt::ArrowCursor));
        testdel = new QPushButton(centralWidget);
        testdel->setObjectName(QStringLiteral("testdel"));
        testdel->setGeometry(QRect(370, 40, 80, 20));
        testdel->setCursor(QCursor(Qt::PointingHandCursor));
        testmov = new QPushButton(centralWidget);
        testmov->setObjectName(QStringLiteral("testmov"));
        testmov->setGeometry(QRect(170, 40, 80, 40));
        testmov->setCursor(QCursor(Qt::PointingHandCursor));
        severon = new QPushButton(centralWidget);
        severon->setObjectName(QStringLiteral("severon"));
        severon->setGeometry(QRect(760, 240, 80, 20));
        severon->setCursor(QCursor(Qt::PointingHandCursor));
        changeGod = new QPushButton(centralWidget);
        changeGod->setObjectName(QStringLiteral("changeGod"));
        changeGod->setGeometry(QRect(370, 60, 80, 20));
        changeGod->setCursor(QCursor(Qt::PointingHandCursor));
        testend = new QPushButton(centralWidget);
        testend->setObjectName(QStringLiteral("testend"));
        testend->setGeometry(QRect(270, 60, 80, 20));
        testend->setCursor(QCursor(Qt::PointingHandCursor));
        teststart = new QPushButton(centralWidget);
        teststart->setObjectName(QStringLiteral("teststart"));
        teststart->setGeometry(QRect(270, 40, 80, 20));
        teststart->setCursor(QCursor(Qt::PointingHandCursor));
        link1 = new QLabel(centralWidget);
        link1->setObjectName(QStringLiteral("link1"));
        link1->setGeometry(QRect(760, 350, 80, 80));
        quitButton1 = new QLabel(centralWidget);
        quitButton1->setObjectName(QStringLiteral("quitButton1"));
        quitButton1->setGeometry(QRect(870, 350, 80, 80));
        equa1 = new QLabel(centralWidget);
        equa1->setObjectName(QStringLiteral("equa1"));
        equa1->setGeometry(QRect(760, 470, 80, 80));
        escape1 = new QLabel(centralWidget);
        escape1->setObjectName(QStringLiteral("escape1"));
        escape1->setGeometry(QRect(870, 470, 80, 80));
        who = new QLabel(centralWidget);
        who->setObjectName(QStringLiteral("who"));
        who->setGeometry(QRect(200, 310, 80, 80));
        walk = new QLabel(centralWidget);
        walk->setObjectName(QStringLiteral("walk"));
        walk->setGeometry(QRect(150, 310, 40, 80));
        chesso = new QLabel(centralWidget);
        chesso->setObjectName(QStringLiteral("chesso"));
        chesso->setGeometry(QRect(160, 459, 120, 31));
        chesse = new QLabel(centralWidget);
        chesse->setObjectName(QStringLiteral("chesse"));
        chesse->setGeometry(QRect(160, 210, 120, 30));
        se = new QLabel(centralWidget);
        se->setObjectName(QStringLiteral("se"));
        se->setGeometry(QRect(850, 160, 80, 20));
        bgm = new QLabel(centralWidget);
        bgm->setObjectName(QStringLiteral("bgm"));
        bgm->setGeometry(QRect(850, 200, 80, 20));
        sever = new QLabel(centralWidget);
        sever->setObjectName(QStringLiteral("sever"));
        sever->setGeometry(QRect(850, 240, 80, 20));
        qh1 = new QLabel(centralWidget);
        qh1->setObjectName(QStringLiteral("qh1"));
        qh1->setGeometry(QRect(160, 260, 120, 30));
        QFont font1;
        font1.setPointSize(16);
        qh1->setFont(font1);
        qh2 = new QLabel(centralWidget);
        qh2->setObjectName(QStringLiteral("qh2"));
        qh2->setGeometry(QRect(160, 410, 120, 30));
        qh2->setFont(font1);
        se_2 = new QLabel(centralWidget);
        se_2->setObjectName(QStringLiteral("se_2"));
        se_2->setGeometry(QRect(760, 160, 80, 20));
        bgm_2 = new QLabel(centralWidget);
        bgm_2->setObjectName(QStringLiteral("bgm_2"));
        bgm_2->setGeometry(QRect(760, 200, 80, 20));
        sever_2 = new QLabel(centralWidget);
        sever_2->setObjectName(QStringLiteral("sever_2"));
        sever_2->setGeometry(QRect(760, 240, 80, 20));
        MainWindow->setCentralWidget(centralWidget);
        label1->raise();
        pushButton_1->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        pushButton_4->raise();
        pushButton_5->raise();
        pushButton_6->raise();
        pushButton_7->raise();
        pushButton_8->raise();
        pushButton_9->raise();
        pushButton_10->raise();
        pushButton_11->raise();
        pushButton_12->raise();
        pushButton_13->raise();
        pushButton_14->raise();
        pushButton_15->raise();
        pushButton_16->raise();
        pushButton_17->raise();
        pushButton_18->raise();
        pushButton_19->raise();
        pushButton_20->raise();
        pushButton_21->raise();
        pushButton_22->raise();
        pushButton_23->raise();
        pushButton_24->raise();
        pushButton_25->raise();
        pushButton_26->raise();
        pushButton_27->raise();
        pushButton_28->raise();
        pushButton_29->raise();
        pushButton_30->raise();
        pushButton_31->raise();
        pushButton_32->raise();
        pushButton_33->raise();
        pushButton_34->raise();
        pushButton_35->raise();
        pushButton_36->raise();
        pushButton_37->raise();
        pushButton_38->raise();
        pushButton_39->raise();
        pushButton_40->raise();
        pushButton_41->raise();
        pushButton_42->raise();
        pushButton_43->raise();
        pushButton_44->raise();
        pushButton_45->raise();
        pushButton_46->raise();
        pushButton_47->raise();
        pushButton_48->raise();
        pushButton_49->raise();
        pushButton_50->raise();
        pushButton_51->raise();
        pushButton_52->raise();
        pushButton_53->raise();
        pushButton_54->raise();
        pushButton_55->raise();
        pushButton_56->raise();
        pushButton_57->raise();
        pushButton_58->raise();
        pushButton_59->raise();
        pushButton_60->raise();
        pushButton_61->raise();
        pushButton_62->raise();
        pushButton_63->raise();
        pushButton_64->raise();
        pushButton_65->raise();
        pushButton_66->raise();
        pushButton_67->raise();
        pushButton_68->raise();
        pushButton_69->raise();
        pushButton_70->raise();
        pushButton_71->raise();
        pushButton_72->raise();
        pushButton_73->raise();
        pushButton_74->raise();
        pushButton_75->raise();
        pushButton_76->raise();
        pushButton_77->raise();
        pushButton_78->raise();
        pushButton_79->raise();
        pushButton_80->raise();
        pushButton_81->raise();
        pushButton_82->raise();
        pushButton_83->raise();
        pushButton_84->raise();
        pushButton_85->raise();
        pushButton_86->raise();
        pushButton_87->raise();
        pushButton_88->raise();
        pushButton_89->raise();
        pushButton_90->raise();
        pushButton_91->raise();
        pushButton_92->raise();
        pushButton_93->raise();
        pushButton_94->raise();
        pushButton_95->raise();
        pushButton_96->raise();
        pushButton_97->raise();
        pushButton_98->raise();
        pushButton_99->raise();
        pushButton_100->raise();
        label_2->raise();
        echess->raise();
        ochess->raise();
        testdel->raise();
        testmov->raise();
        changeGod->raise();
        testend->raise();
        teststart->raise();
        link1->raise();
        quitButton1->raise();
        equa1->raise();
        escape1->raise();
        equa->raise();
        escape->raise();
        link->raise();
        quitButton->raise();
        walk->raise();
        who->raise();
        chesso->raise();
        chesse->raise();
        se->raise();
        bgm->raise();
        sever->raise();
        qh1->raise();
        qh2->raise();
        se_2->raise();
        sebut->raise();
        bgm_2->raise();
        bgmbut->raise();
        sever_2->raise();
        severon->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        pushButton_1->setText(QString());
        pushButton_2->setText(QString());
        pushButton_3->setText(QString());
        pushButton_4->setText(QString());
        pushButton_5->setText(QString());
        pushButton_6->setText(QString());
        pushButton_7->setText(QString());
        pushButton_8->setText(QString());
        pushButton_9->setText(QString());
        pushButton_10->setText(QString());
        pushButton_11->setText(QString());
        pushButton_12->setText(QString());
        pushButton_13->setText(QString());
        pushButton_14->setText(QString());
        pushButton_15->setText(QString());
        pushButton_16->setText(QString());
        pushButton_17->setText(QString());
        pushButton_18->setText(QString());
        pushButton_19->setText(QString());
        pushButton_20->setText(QString());
        pushButton_21->setText(QString());
        pushButton_22->setText(QString());
        pushButton_23->setText(QString());
        pushButton_24->setText(QString());
        pushButton_25->setText(QString());
        pushButton_26->setText(QString());
        pushButton_27->setText(QString());
        pushButton_28->setText(QString());
        pushButton_29->setText(QString());
        pushButton_30->setText(QString());
        pushButton_31->setText(QString());
        pushButton_32->setText(QString());
        pushButton_33->setText(QString());
        pushButton_34->setText(QString());
        pushButton_35->setText(QString());
        pushButton_36->setText(QString());
        pushButton_37->setText(QString());
        pushButton_38->setText(QString());
        pushButton_39->setText(QString());
        pushButton_40->setText(QString());
        pushButton_41->setText(QString());
        pushButton_42->setText(QString());
        pushButton_43->setText(QString());
        pushButton_44->setText(QString());
        pushButton_45->setText(QString());
        pushButton_46->setText(QString());
        pushButton_47->setText(QString());
        pushButton_48->setText(QString());
        pushButton_49->setText(QString());
        pushButton_50->setText(QString());
        pushButton_51->setText(QString());
        pushButton_52->setText(QString());
        pushButton_53->setText(QString());
        pushButton_54->setText(QString());
        pushButton_55->setText(QString());
        pushButton_56->setText(QString());
        pushButton_57->setText(QString());
        pushButton_58->setText(QString());
        pushButton_59->setText(QString());
        pushButton_60->setText(QString());
        pushButton_61->setText(QString());
        pushButton_62->setText(QString());
        pushButton_63->setText(QString());
        pushButton_64->setText(QString());
        pushButton_65->setText(QString());
        pushButton_66->setText(QString());
        pushButton_67->setText(QString());
        pushButton_68->setText(QString());
        pushButton_69->setText(QString());
        pushButton_70->setText(QString());
        pushButton_71->setText(QString());
        pushButton_72->setText(QString());
        pushButton_73->setText(QString());
        pushButton_74->setText(QString());
        pushButton_75->setText(QString());
        pushButton_76->setText(QString());
        pushButton_77->setText(QString());
        pushButton_78->setText(QString());
        pushButton_79->setText(QString());
        pushButton_80->setText(QString());
        pushButton_81->setText(QString());
        pushButton_82->setText(QString());
        pushButton_83->setText(QString());
        pushButton_84->setText(QString());
        pushButton_85->setText(QString());
        pushButton_86->setText(QString());
        pushButton_87->setText(QString());
        pushButton_88->setText(QString());
        pushButton_89->setText(QString());
        pushButton_90->setText(QString());
        pushButton_91->setText(QString());
        pushButton_92->setText(QString());
        pushButton_93->setText(QString());
        pushButton_94->setText(QString());
        pushButton_95->setText(QString());
        pushButton_96->setText(QString());
        pushButton_97->setText(QString());
        pushButton_98->setText(QString());
        pushButton_99->setText(QString());
        pushButton_100->setText(QString());
        label1->setText(QString());
        quitButton->setText(QString());
        label_2->setText(QString());
        equa->setText(QString());
        escape->setText(QString());
        link->setText(QString());
        sebut->setText(QString());
        bgmbut->setText(QString());
        testdel->setText(QApplication::translate("MainWindow", "\346\265\213\350\257\225\347\224\250 \345\210\240\351\231\244", 0));
        testdel->setShortcut(QApplication::translate("MainWindow", "Del", 0));
        testmov->setText(QApplication::translate("MainWindow", "\346\265\213\350\257\225\346\250\241\345\274\217 : \351\227\234", 0));
        severon->setText(QString());
        changeGod->setText(QApplication::translate("MainWindow", "\346\265\213\350\257\225 \347\216\213", 0));
        testend->setText(QApplication::translate("MainWindow", "\347\265\220\346\235\237\345\233\236\345\220\210", 0));
        teststart->setText(QApplication::translate("MainWindow", "\351\226\213\345\247\213\345\233\236\345\220\210", 0));
        link1->setText(QString());
        quitButton1->setText(QApplication::translate("MainWindow", "l", 0));
        equa1->setText(QString());
        escape1->setText(QString());
        who->setText(QString());
        walk->setText(QString());
        chesso->setText(QString());
        chesse->setText(QString());
        se->setText(QString());
        bgm->setText(QString());
        sever->setText(QString());
        qh1->setText(QString());
        qh2->setText(QString());
        se_2->setText(QString());
        bgm_2->setText(QString());
        sever_2->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
