all:
	g++ *.cpp -o main
debug:
	g++ -DDEBUG  -o main *.cpp
minus:
	g++ -DMINUS  -o main *.cpp
product:
	g++ -DPRODUCT  -o main *.cpp
divide:
	g++ -DDIVIDE  -o main *.cpp
clean: 
	rm -f main