xlabel('T');
ylabel('P(T|wi)');
hold on;
P=0.6;
d=111;
k=0:d;
y=binopdf(k,d,P);
plot(k/d,y);
hold on;
d=11;
k=0:d;
y=binopdf(k,d,P);
plot(k/d,y);
hold on;
P=0.4;
d=111;
k=0:d;
y=binopdf(k,d,P);
plot(k/d,y);
hold on;
d=11;
k=0:d;
y=binopdf(k,d,P);
plot(k/d,y);
legend('d=111,P(T|w1)','d=11,P(T|w1)','d=111,P(T|w2)','d=11,P(T|w2)');