all: exe_1 exe_2 exe_3 exe_4

exe_1: main.cpp
	g++ main.cpp -o exe_1 -std=c++11 -Dsubtask1

exe_2: main.cpp
	g++ main.cpp -o exe_2 -std=c++11 -Dsubtask2

exe_3: main.cpp
	g++ main.cpp -o exe_3 -std=c++11 -Dsubtask3

exe_4: main.cpp
	g++ main.cpp -o exe_4 -std=c++11 -Dsubtask4

clean:
	rm exe*